#!/usr/bin/env node
/* ============================================================
   WA AGENT — compilador del cliente activo (cero deps)

   Uso:  node tools/compile-kb.mjs            (cliente por defecto: md-condesa)
         CLIENT=iasmin node tools/compile-kb.mjs

   Cada cliente vive en clients/<id>/ :
     - client.mjs      → configuración del negocio (default export)
     - persona.md      → persona + políticas duras (system prompt)
     - intake.md       → contenido del KB editado a mano (fuente de verdad)
     - kb-build.mjs    → (opcional) constructor de KB a la medida; exporta
                         buildKb({ intake, cfg }) → { body, slots, sources }.
                         Sin este archivo, el KB es intake.md VERBATIM y los
                         slots vienen de cfg.slots (o ninguno).

   Salidas (todas se COMMITEAN; reflejan el ÚLTIMO cliente compilado —
   compila md-condesa antes de commitear si tocaste otro cliente):
     - kb/compiled/kb.md         → texto importado por src/kb.ts
     - kb/compiled/slots.json    → slots válidos (referencia legible)
     - src/brain/slots.gen.ts    → mismos slots como const tipado
     - src/client.gen.ts         → ClientConfig del cliente activo

   Falla (exit 1) si el KB supera ~6000 tokens (chars/3.5).
============================================================ */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = join(__dirname, "..");
const TOKEN_LIMIT = 9000;

async function main() {
  const clientId = process.env.CLIENT || "md-condesa";
  const clientDir = join(REPO, "clients", clientId);
  if (!existsSync(join(clientDir, "client.mjs"))) {
    throw new Error(
      `clients/${clientId}/client.mjs no existe. Clientes disponibles: revisa clients/.`,
    );
  }

  const cfg = (await import(pathToFileURL(join(clientDir, "client.mjs")).href)).default;
  if (cfg.clientId !== clientId) {
    throw new Error(
      `clients/${clientId}/client.mjs declara clientId '${cfg.clientId}' — deben coincidir.`,
    );
  }
  const persona = readFileSync(join(clientDir, "persona.md"), "utf8").trimEnd();
  const intake = readFileSync(join(clientDir, "intake.md"), "utf8");

  // KB body + slots: custom builder when the client has one, else generic.
  const kbBuildPath = join(clientDir, "kb-build.mjs");
  let built;
  if (existsSync(kbBuildPath)) {
    const mod = await import(pathToFileURL(kbBuildPath).href);
    built = await mod.buildKb({ intake, cfg });
  } else {
    built = genericKb(intake, cfg);
  }
  const { body, slots = [], sources = "intake.md" } = built;

  const hash = createHash("sha256").update(body).digest("hex").slice(0, 12);
  const date = new Date().toISOString().slice(0, 10);
  const version = `${date}+${hash}`;
  const approxTokens = Math.ceil(body.length / 3.5);

  const header =
    `<!-- KB compilado por tools/compile-kb.mjs — NO editar a mano.\n` +
    `     version: ${version}\n` +
    `     approx_tokens: ${approxTokens} (chars ${body.length} / 3.5)\n` +
    `     fuentes: ${sources} -->\n\n`;

  // Emit outputs.
  const compiledDir = join(REPO, "kb", "compiled");
  mkdirSync(compiledDir, { recursive: true });
  writeFileSync(join(compiledDir, "kb.md"), header + body);
  writeFileSync(
    join(compiledDir, "slots.json"),
    JSON.stringify({ version, slots }, null, 2) + "\n",
  );

  writeFileSync(join(REPO, "src", "brain", "slots.gen.ts"), renderSlotsTs(slots, version));
  writeFileSync(join(REPO, "src", "client.gen.ts"), renderClientTs(cfg, persona, version));

  console.log(
    `[${clientId}] KB compiled → kb/compiled/kb.md (${approxTokens} tok, ${slots.length} slots) [${version}]`,
  );

  if (approxTokens > TOKEN_LIMIT) {
    console.error(
      `FAIL: KB ~${approxTokens} tokens exceeds limit ${TOKEN_LIMIT}. Trim content.`,
    );
    process.exit(1);
  }

  if (cfg.features?.safety && !cfg.safety) {
    console.error(`FAIL: features.safety está activo pero falta el bloque 'safety' en client.mjs.`);
    process.exit(1);
  }
  if (cfg.features?.booking && slots.length === 0) {
    console.warn(
      `WARN: features.booking está activo pero no hay slots — book_trial rechazará todo.`,
    );
  }
}

/** Generic KB: a one-line header + the client's intake.md verbatim. */
function genericKb(intake, cfg) {
  const body = [
    `# ${cfg.businessName} — Knowledge Base`,
    "",
    intake.trim(),
    "",
  ].join("\n");
  return { body, slots: cfg.slots ?? [], sources: "intake.md" };
}

function renderSlotsTs(slots, version) {
  const rows = slots
    .map(
      (s) =>
        `  { weekday: ${s.weekday}, time: ${JSON.stringify(s.time)}, discipline: ${JSON.stringify(s.discipline)}, audience: ${JSON.stringify(s.audience)} },`,
    )
    .join("\n");
  return (
    `// GENERATED by tools/compile-kb.mjs — do not edit. version: ${version}\n` +
    `// Valid booking slots flattened from the client schedule. weekday: 0=Mon … 6=Sun.\n` +
    `export interface Slot {\n` +
    `  weekday: number;\n` +
    `  time: string; // "HH:mm" 24h, America/Mexico_City\n` +
    `  discipline: string; // service key (see src/client.gen.ts services)\n` +
    `  audience: "adult" | "kid";\n` +
    `}\n\n` +
    `export const SLOTS: readonly Slot[] = [\n${rows}\n];\n`
  );
}

function renderClientTs(cfg, persona, version) {
  // Persona rides in from persona.md; everything else from client.mjs. The
  // object is emitted as literal TS so the worker bundles it with zero I/O.
  const obj = {
    clientId: cfg.clientId,
    businessName: cfg.businessName,
    shortName: cfg.shortName,
    ownerName: cfg.ownerName,
    address: cfg.address ?? "",
    links: {
      booking: cfg.links?.booking ?? "",
      bookingKids: cfg.links?.bookingKids ?? cfg.links?.booking ?? "",
      schedule: cfg.links?.schedule ?? cfg.links?.booking ?? "",
    },
    services: cfg.services ?? [],
    persona,
    features: {
      booking: !!cfg.features?.booking,
      nudges: !!cfg.features?.nudges,
      airtableSync: !!cfg.features?.airtableSync,
      safety: !!cfg.features?.safety,
    },
    ...(cfg.safety ? { safety: cfg.safety } : {}),
    copy: cfg.copy,
  };
  return (
    `// GENERATED by tools/compile-kb.mjs — do not edit.\n` +
    `// client: ${cfg.clientId} · version: ${version}\n` +
    `// Source: clients/${cfg.clientId}/client.mjs + persona.md\n` +
    `import type { ClientConfig } from "./client-config.js";\n\n` +
    `export const CLIENT: ClientConfig = ${JSON.stringify(obj, null, 2)};\n`
  );
}

main().catch((err) => {
  console.error("compile-kb failed:", err);
  process.exit(1);
});
