#!/usr/bin/env node
/* ============================================================
   WA AGENT — huella de despliegue (cero deps)

   Uso:  node tools/gen-rev.mjs      (corre dentro de `npm run build`)

   kbVersion sólo cambia cuando cambia el CONTENIDO del KB, así que un
   deploy de puro código es invisible en /health. REV cierra ese hueco:
   hashea el árbol fuente que se embarca — todo .ts bajo src/ más
   src/ui/admin.html, en orden de ruta, con la ruta metida en el digest
   para que los renames también cuenten.

   src/rev.gen.ts queda EXCLUIDO: si entrara, el hash se perseguiría la
   cola y nunca sería estable.

   Salida (se COMMITEA): src/rev.gen.ts
============================================================ */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join, relative, sep } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = join(__dirname, "..");
const SRC = join(REPO, "src");
const OUT = join(SRC, "rev.gen.ts");
const ADMIN_HTML = join(SRC, "ui", "admin.html");

function walk(dir, acc = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) walk(p, acc);
    else if (entry.isFile()) acc.push(p);
  }
  return acc;
}

const files = walk(SRC)
  .filter((p) => p !== OUT && (p.endsWith(".ts") || p === ADMIN_HTML))
  .map((p) => relative(REPO, p).split(sep).join("/"))
  .sort();

// Bytes, not text: src/routes/admin-api.ts carries intentional NUL bytes.
const digest = createHash("sha256");
for (const rel of files) {
  digest.update(rel);
  digest.update("\0");
  digest.update(readFileSync(join(REPO, rel)));
  digest.update("\0");
}
const rev = digest.digest("hex").slice(0, 12);

writeFileSync(
  OUT,
  `// GENERATED by tools/gen-rev.mjs — NEVER hand-edit.\n` +
    `// Content hash of the source tree this build ships (src/**/*.ts +\n` +
    `// src/ui/admin.html). Surfaced as /health rev so a code-only deploy can\n` +
    `// be verified: re-run tools/gen-rev.mjs at a commit and compare.\n` +
    `export const REV: string = ${JSON.stringify(rev)};\n`,
);

console.log(`[rev] ${rev} (${files.length} files) → src/rev.gen.ts`);
