// GENERATED by tools/gen-rev.mjs — NEVER hand-edit.
// Content hash of the source tree this build ships (src/**/*.ts +
// src/ui/admin.html). Surfaced as /health rev so a code-only deploy can
// be verified: re-run tools/gen-rev.mjs at a commit and compare.
export const REV: string = "40056eea736b";
